### ISSUE TITLE
Support for URLs too

### ISSUE THREAD

**Issue by eliasdorneles** [rolando/parsel-cli#2]
Currently, the input for `parsel-cli` is HTML data read either from stdin or from a local file.

It would be nice to support URLs too, as in: `parsel-cli EXPR http://example.com`.

This would probably need adding the `requests` dependency to fetch the page.

**Comment by rmax** [comment]
Sounds good to me 👍

**Comment by rmax** [comment]
Fixed in latest release.

**Comment by eliasdorneles** [comment]
Yay, thank you!!
